apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      restartPolicy: Always
      containers:
      - name: rails-container
        image: arunprasathuj/budget-app-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: postgresql://admin:password@postgres:5432/Budgy_development
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: Budgy_development

